# Deber Descomposicion LU

**1. Realice las siguientes multiplicaciones matriz-matriz:**


In [8]:

import numpy as np

A = np.array([[2,-3],
              [3, -1]])  

B = np.array([[1, 5],
              [2, 0]])  


C = np.dot(A, B) # Multiplicación

print("Resultado de la multiplicación:")
print(C)

Resultado de la multiplicación:
[[-4 10]
 [ 1 15]]


In [9]:

A = np.array([[2,-3],
              [3, -1]])  

B = np.array([[1, 5,-4],
              [-3, 2, 0]])  


C = np.dot(A, B) # Multiplicación

print("Resultado de la multiplicación:")
print(C)

Resultado de la multiplicación:
[[ 11   4  -8]
 [  6  13 -12]]


In [10]:

A = np.array([[2,-3, 1],
              [4, 3, 0],
              [5, 2, -4]])  

B = np.array([[0, 1,-2],
              [1, 0, -1],
              [2, 3, -2]])  


C = np.dot(A, B) # Multiplicación

print("Resultado de la multiplicación:")
print(C)

Resultado de la multiplicación:
[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


In [11]:

A = np.array([[2, 1, 2],
              [-2, 3, 0],
              [2, -1, 3]])  

B = np.array([[1, -2],
              [-4, 1],
              [0, 2]])  


C = np.dot(A, B) # Multiplicación

print("Resultado de la multiplicación:")
print(C)

Resultado de la multiplicación:
[[ -2   1]
 [-14   7]
 [  6   1]]


**2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:**

In [16]:
import numpy as np
from funciones_matrices import es_no_singular, calcular_inversa

# Matriz
A = np.array([[4, 2, 6],
              [3, 0, 7],
              [-2, -1, -3]])  

# Verificar si es no singular
if es_no_singular(A):
    print("La matriz A es no singular.")
    
    # Para calcular la inversa
    inversa_A = calcular_inversa(A)
    print("La inversa de A es:")
    print(inversa_A)
else:
    print("La matriz A es singular y no tiene inversa.")

La matriz A es singular y no tiene inversa.


In [17]:
import numpy as np
from funciones_matrices import es_no_singular, calcular_inversa

# Matriz
A = np.array([[1, 2, 0],
              [2, 1, -1],
              [3, 1, 1]])  

# Verificar si es no singular
if es_no_singular(A):
    print("La matriz A es no singular.")
    
    # Para calcular la inversa
    inversa_A = calcular_inversa(A)
    print("La inversa de A es:")
    print(inversa_A)
else:
    print("La matriz A es singular y no tiene inversa.")

La matriz A es no singular.
La inversa de A es:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]


In [18]:
import numpy as np
from funciones_matrices import es_no_singular, calcular_inversa

# Matriz
A = np.array([[1, 1, -1, 1],
              [1, 2, -4, -2],
              [2, 1, 1, 5],
              [-1, 0, -2, -4]])  

# Verificar si es no singular
if es_no_singular(A):
    print("La matriz A es no singular.")
    
    # Para calcular la inversa
    inversa_A = calcular_inversa(A)
    print("La inversa de A es:")
    print(inversa_A)
else:
    print("La matriz A es singular y no tiene inversa.")

La matriz A es singular y no tiene inversa.


In [19]:
import numpy as np
from funciones_matrices import es_no_singular, calcular_inversa

# Matriz
A = np.array([[4, 0, 0, 0],
              [6, 7, 0, 0],
              [9, 11, 1, 0],
              [5, 4, 1, 1]])   

# Verificar si es no singular
if es_no_singular(A):
    print("La matriz A es no singular.")
    
    # Para calcular la inversa
    inversa_A = calcular_inversa(A)
    print("La inversa de A es:")
    print(inversa_A)
else:
    print("La matriz A es singular y no tiene inversa.")

La matriz A es no singular.
La inversa de A es:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]


**3. Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:**

In [32]:
import numpy as np

def resolver_sistema(A, b):
    """
    Resuelve un sistema de ecuaciones lineales Ax = b, donde A es una matriz 4x4 y b es un vector de tamaño 4.
    
    Parámetros:
        A (numpy.ndarray): Matriz de coeficientes de tamaño 4x4.
        b (numpy.ndarray): Vector de términos independientes de tamaño 4.
    
    Retorna:
        x (numpy.ndarray): Solución del sistema de ecuaciones.
    """
    # Verificar que A sea una matriz 4x4 y b sea un vector de tamaño 4
    if A.shape != (4, 4) or b.shape != (4,):
        raise ValueError("La matriz A debe ser 4x4 y el vector b debe ser de tamaño 4.")
    
    # Resolver el sistema de ecuaciones
    x = np.linalg.solve(A, b)
    return x


# Definir la matriz A    
A = np.array([[1, -1, 2, -1],
              [1, 0, -1, 1],
              [2, 1, 3, -4],
              [0, -1, 1, -1]])  

b = np.array([6, 4, -2, 5])  # el vector b de términos independientes

# Resolver el sistema de ecuaciones
try:
    x = resolver_sistema(A, b)
    print("La solución del sistema es:")
    print(x)
except ValueError as e:
    print(e)

La solución del sistema es:
[ 3. -6. -2. -1.]


In [33]:
# Definir la matriz A (4x4) y el vector b (4)
A = np.array([[1, -1, 2, -1],
              [1, 0, -1, 1],
              [2, 1, 3, -4],
              [0, -1, 1, -1]]) 

b = np.array([1, 1, 2, -1])  # Vector de términos independientes

# Resolver el sistema de ecuaciones
try:
    x = resolver_sistema(A, b)
    print("La solución del sistema es:")
    print(x)
except ValueError as e:
    print(e)

La solución del sistema es:
[1. 1. 1. 1.]


**4. Encuentre los valores de A que hacen que la siguiente matriz sea singular.**

In [34]:
import numpy as np

# Definir la matriz A en función de alpha
def matriz_A(alpha):
    return np.array([[1, -1, alpha],
                     [2, 2, 1],
                     [0, alpha, -3/2]])

# Calcular el determinante de A
def determinante_A(alpha):
    return np.linalg.det(matriz_A(alpha))

# Valores de alpha que hacen que A sea singular
alpha_1 = 2
alpha_2 = -3/2

# Verificar que el determinante es cero para estos valores
print(f"Determinante para alpha = {alpha_1}: {determinante_A(alpha_1)}")
print(f"Determinante para alpha = {alpha_2}: {determinante_A(alpha_2)}")

Determinante para alpha = 2: 0.0
Determinante para alpha = -1.5: 0.0


**5.- Resuelva los siguientes sistemas lineales:**

**a)**

In [41]:
import numpy as np

A = np.array([[1, 0, 0],
              [2, 1, 0],
              [-1, 0, 1]])  

B = np.array([[2, 3, -1],
              [0, -2, 1],
              [0, 0, 3]])  


C = np.dot(A, B)
print('La Matriz C es:')
print(C)

b = np.array([2, -1, 1])

x = np.linalg.solve(C, b)
print("Solución del sistema es:")
print(x)

La Matriz C es:
[[ 2  3 -1]
 [ 4  4 -1]
 [-2 -3  4]]
Solución del sistema es:
[-3.  3.  1.]


**b)**

In [43]:
import numpy as np

A = np.array([[2, 0, 0],
              [-1, 1, 0],
              [3, 2, -1]])  

B = np.array([[1, 1, 1],
              [0, 1, 2],
              [0, 0, 1]])  


C = np.dot(A, B)
print('La Matriz C es:')
print(C)

b = np.array([-1, 3, 0])

x = np.linalg.solve(C, b)
print("Solución del sistema es:")
print(x)

La Matriz C es:
[[ 2  2  2]
 [-1  0  1]
 [ 3  5  6]]
Solución del sistema es:
[ 0.5 -4.5  3.5]


**6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU
con lii = 1 para todas las i.**

**a)**

In [60]:
import numpy as np
from scipy.linalg import lu

# Definir las matrices
A_a = np.array([[2, -1, 1],
                [3, 3, 9],
                [3, 3, 5]])


# Función para factorización LU
def factorizacion_lu(A):
    P, L, U = lu(A)
    return P, L, U

# Aplicar la factorización LU a cada matriz
P_a, L_a, U_a = factorizacion_lu(A_a)


print("Matriz A:")
print("L:")
print(L_a)
print("U:")
print(U_a)


Matriz A:
L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
U:
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]


**b)**

In [57]:
import numpy as np
from scipy.linalg import lu


B = np.array([[1.012, -2.132, 3.104],
                [-2.132, 4.096, -7.013],
                [3.104, -7.013, 0.014]])


# Función para factorización LU
def factorizacion_lu(A):
    P, L, U = lu(A)
    return P, L, U

# Aplicar la factorización LU 
P_b, L_b, U_b = factorizacion_lu(B)


print("\nMatriz A_b:")
print("L:")
print(L_b)
print("U:")
print(U_b)


Matriz A_b:
L:
[[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
U:
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]


**c)**

In [58]:
import numpy as np
from scipy.linalg import lu

# Matriz
C = np.array([[2, 0, 0, 0],
                [1, 1.5, 0, 0],
                [0, -3, 0.5, 0],
                [2, -2, 1, 1]])


# Función para factorización LU
def factorizacion_lu(A):
    P, L, U = lu(A)
    return P, L, U

# Aplicar la factorización LU 
P_c, L_c, U_c = factorizacion_lu(C)


print("\nMatriz C:")
print("L:")
print(L_c)
print("U:")
print(U_c)



Matriz C:
L:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]
U:
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]


**d)**

In [59]:
import numpy as np
from scipy.linalg import lu

D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
                [-4.0231, 6.0000, 0, 1.1973],
                [-1.0000, -5.2107, 1.1111, 0],
                [6.0235, 7.0000, 0, -4.1561]])

# Función para factorización LU
def factorizacion_lu(A):
    P, L, U = lu(A)
    return P, L, U

# Aplicar la factorización LU 
P_d, L_d, U_d = factorizacion_lu(D)


print("\nMatriz D:")
print("L:")
print(L_d)
print("U:")
print(U_d)


Matriz D:
L:
[[ 1.          0.          0.          0.        ]
 [-0.66790072  1.          0.          0.        ]
 [ 0.36118536  0.14002434  1.          0.        ]
 [-0.16601644 -0.37924771 -0.5112737   1.        ]]
U:
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.          0.         -2.1732      6.91885959]
 [ 0.          0.          0.          2.24878393]]


**7) Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema
lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.**

In [69]:
import numpy as np

def eliminacion_gaussiana_lu(A: np.ndarray):
    """Realiza la descomposición LU de una matriz A usando eliminación gaussiana.

    ## Parameters

    ``A``: matriz de coeficientes del sistema de ecuaciones lineales. Debe ser de tamaño n-by-n.

    ## Return

    ``L``: matriz triangular inferior con unos en la diagonal.
    ``U``: matriz triangular superior.
    """
    if not isinstance(A, np.ndarray):
        print("Convirtiendo A a numpy array.")
        A = np.array(A)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.eye(n)  # Matriz identidad (L tendrá unos en la diagonal)
    U = A.copy()   # Copia de A para convertirse en U

    for i in range(n - 1):  # loop por columna
        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if U[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(U[pi, i]) < abs(U[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            print(f"Intercambiando filas {i} y {p}")
            _aux = U[i, :].copy()
            U[i, :] = U[p, :].copy()
            U[p, :] = _aux

            # También intercambiar las filas correspondientes en L
            _aux = L[i, :i].copy()
            L[i, :i] = L[p, :i].copy()
            L[p, :i] = _aux

        # --- Eliminación: loop por fila
        for j in range(i + 1, n):
            m = U[j, i] / U[i, i]
            L[j, i] = m  # Guardar el multiplicador en L
            U[j, i:] = U[j, i:] - m * U[i, i:]

        print(f"\nL:\n{L}\nU:\n{U}")

    return L, U

def sustitucion_adelante(L, b):
    """Resuelve el sistema Ly = b usando sustitución hacia adelante.

    ## Parameters

    ``L``: matriz triangular inferior con unos en la diagonal.
    ``b``: vector de términos independientes.

    ## Return

    ``y``: vector solución.
    """
    n = L.shape[0]
    y = np.zeros(n)

    for i in range(n):
        suma = np.dot(L[i, :i], y[:i])
        y[i] = (b[i] - suma) / L[i, i]

    return y

def sustitucion_atras(U, y):
    """Resuelve el sistema Ux = y usando sustitución hacia atrás.

    ## Parameters

    ``U``: matriz triangular superior.
    ``y``: vector solución de Ly = b.

    ## Return

    ``x``: vector solución.
    """
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n - 1, -1, -1):
        suma = np.dot(U[i, i + 1:], x[i + 1:])
        x[i] = (y[i] - suma) / U[i, i]

    return x

def resolver_sistema_lu(A, b):
    """Resuelve el sistema Ax = b usando la descomposición LU.

    ## Parameters

    ``A``: matriz de coeficientes del sistema de ecuaciones lineales.
    ``b``: vector de términos independientes.

    ## Return

    ``x``: vector solución.
    """
    L, U = eliminacion_gaussiana_lu(A)
    y = sustitucion_adelante(L, b)
    x = sustitucion_atras(U, y)
    return x

# Ejemplo de uso
A = np.array([[2, -1, 1],
              [3, 3, 9],
              [3, 3, 5]])

b = np.array([2, -1, 1])

x = resolver_sistema_lu(A, b)
print("Solución del sistema A:")
print(x)


L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 0.  1. ]]
U:
[[ 2 -1  1]
 [ 0  4  7]
 [ 0  4  3]]

L:
[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]
U:
[[ 2 -1  1]
 [ 0  4  7]
 [ 0  0 -4]]
Solución del sistema A:
[ 1.1875 -0.125  -0.5   ]


In [68]:
B = np.array([[1.012, -2.132, 3.104],
                [-2.132, 4.096, -7.013],
                [3.104, -7.013, 0.014]])

b = np.array([1.984, -5.049, -3.895])

x = resolver_sistema_lu(B, b)
print("Solución del sistema B:")
print(x)


L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  0.          1.        ]]
U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]

L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
Solución del sistema B:
[1. 1. 1.]


In [67]:
C = np.array([[2, 0, 0, 0],
                [1, 1.5, 0, 0],
                [0, -3, 0.5, 0],
                [2, -2, 1, 1]])

b = np.array([3, 4.5, -6.6, 0.8])

x = resolver_sistema_lu(B, b)
print("Solución del sistema C:")
print(x)


L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  0.          1.        ]]
U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]

L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
Solución del sistema C:
[-72.6552259  -31.21014922   3.2174776 ]


In [66]:
D = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
                [-4.0231, 6.0000, 0, 1.1973],
                [-1.0000, -5.2107, 1.1111, 0],
                [6.0235, 7.0000, 0, -4.1561]])

b = np.array([17.102, -6.1593, 3.0004, 0])

x = resolver_sistema_lu(B, b)
print("Solución del sistema D:")
print(x)


L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  0.          1.        ]]
U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.         -0.47374308 -9.50656917]]

L:
[[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]
U:
[[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]
Solución del sistema D:
[-195.50238733  -86.93944465    9.53463917]
