# Tarea #11: Gauss Seidel y Jacobi

**1. Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por
medio de 𝐱
(𝟎) = 0:**

In [3]:
import numpy as np

def jacobi(A, b, x0, iterations):
    """
    Método de Jacobi para resolver un sistema Ax = b.

    Parámetros:
    A -- Matriz de coeficientes
    b -- Vector de términos independientes
    x0 -- Vector inicial
    iterations -- Número de iteraciones

    Retorna:
    x -- Aproximación después de las iteraciones
    """
    D = np.diag(np.diag(A))  # Matriz diagonal
    R = A - D  # Parte restante de A
    D_inv = np.linalg.inv(D)  # Inversa de la diagonal

    x = x0.copy()
    for i in range(iterations):
        x = np.dot(D_inv, b - np.dot(R, x))
        print(f"Iteración {i+1}: {x}")

    return x

In [4]:
# Sistema a)
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema a):")
jacobi(A, b, x0, iterations)


Sistema a):
Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]


array([ 0.14285714, -0.35714286,  0.42857143])

In [5]:
# Sistema b)
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema b):")
jacobi(A, b, x0, iterations)

Sistema b):
Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]


array([0.97, 0.91, 0.74])

In [7]:
# Sistema c)
A = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8,1], [0, 0, 1, 5]])
b = np.array([6, 25, -11, 11])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema c):")
jacobi(A, b, x0, iterations)

Sistema c):
Iteración 1: [ 0.6    2.5   -1.375  2.2  ]
Iteración 2: [-0.65   1.65  -0.4    2.475]


array([-0.65 ,  1.65 , -0.4  ,  2.475])

In [10]:
# Sistema d)
A = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5,-1,-1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6,6])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema d):")
jacobi(A, b, x0, iterations)

Sistema d):
Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]


array([ 1.325, -1.6  ,  1.6  ,  1.675,  2.425])

**2) Repita el ejercicio 1 usando el método de Gauss-Siedel.**

In [19]:
import numpy as np

def gauss_seidel(A, b, x0, iterations):
    """
    Método de Gauss-Seidel para resolver un sistema Ax = b.

    Parámetros:
    A -- Matriz de coeficientes
    b -- Vector de términos independientes
    x0 -- Vector inicial
    iterations -- Número de iteraciones

    Retorna:
    x -- Aproximación después de las iteraciones
    """
    n = len(A)
    x = x0.copy()

    for k in range(iterations):
        x_new = x.copy()
        for i in range(n):
            sum1 = sum(A[i][j] * x_new[j] for j in range(i))  # Elementos antes de x_i (actualizados)
            sum2 = sum(A[i][j] * x[j] for j in range(i + 1, n))  # Elementos después de x_i (sin actualizar)
            x_new[i] = (b[i] - sum1 - sum2) / A[i][i]  # Nueva aproximación de x_i

        x = x_new
        print(f"Iteración {k+1}: {x}")

    return x



In [20]:
# Sistema a)
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema a) con Gauss-Seidel:")
gauss_seidel(A, b, x0, iterations)


Sistema a) con Gauss-Seidel:
Iteración 1: [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762]


array([ 0.11111111, -0.22222222,  0.61904762])

In [22]:
# Sistema b)
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema b) con Gauss-Seidel:")
gauss_seidel(A, b, x0, iterations)

Sistema b) con Gauss-Seidel:
Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]


array([0.979 , 0.9495, 0.7899])

In [23]:
# Sistema c)
A = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8,1], [0, 0, 1, 5]])
b = np.array([6, 25, -11, 11])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema b) con Gauss-Seidel:")
gauss_seidel(A, b, x0, iterations)

Sistema b) con Gauss-Seidel:
Iteración 1: [ 0.6    2.2   -0.275  2.255]
Iteración 2: [-0.5       2.64     -0.336875  2.267375]


array([-0.5     ,  2.64    , -0.336875,  2.267375])

In [24]:
# Sistema d)
A = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5,-1,-1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6,6])
x0 = np.zeros(len(b))  # x(0) = 0
iterations = 2  # Primeras dos iteraciones

print("Sistema b) con Gauss-Seidel:")
gauss_seidel(A, b, x0, iterations)

Sistema b) con Gauss-Seidel:
Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]


array([ 1.1890625 , -1.52135417,  1.86239583,  1.88252604,  2.25564453])

**3. Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3**

In [12]:
import numpy as np

def jacobi(A, b, x0, tol=1e-3, max_iterations=100):
    """
    Método de Jacobi para resolver un sistema Ax = b con tolerancia.

    Parámetros:
    A -- Matriz de coeficientes
    b -- Vector de términos independientes
    x0 -- Vector inicial
    tol -- Tolerancia para la convergencia
    max_iterations -- Máximo número de iteraciones permitidas

    Retorna:
    x -- Aproximación de la solución
    """
    D = np.diag(np.diag(A))  # Matriz diagonal
    R = A - D  # Parte restante de A
    D_inv = np.linalg.inv(D)  # Inversa de la diagonal

    x = x0.copy()
    for i in range(max_iterations):
        x_new = np.dot(D_inv, b - np.dot(R, x))
        
        # Criterio de parada: norma de la diferencia entre iteraciones
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Convergencia alcanzada en {i+1} iteraciones")
            return x_new
        
        x = x_new
        print(f"Iteración {i+1}: {x}")

    print("Se alcanzó el máximo de iteraciones sin convergencia")
    return x




In [13]:
# Sistema a)
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = np.zeros(len(b))  # x(0) = 0

print("Sistema a):")
solucion = jacobi(A, b, x0)
print("Solución aproximada:", solucion)

Sistema a):
Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]
Iteración 3: [ 0.07142857 -0.21428571  0.66326531]
Iteración 4: [ 0.04081633 -0.25680272  0.63265306]
Iteración 5: [ 0.03684807 -0.23129252  0.66399417]
Iteración 6: [ 0.03490444 -0.23975543  0.6547619 ]
Iteración 7: [ 0.03516089 -0.23570619  0.65922185]
Iteración 8: [ 0.03502399 -0.23732106  0.65737656]
Convergencia alcanzada en 9 iteraciones
Solución aproximada: [ 0.03510079 -0.23663751  0.65812732]


In [15]:
# Sistema b)
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = np.zeros(len(b))  # x(0) = 0

print("Sistema b):")
solucion = jacobi(A, b, x0)
print("Solución aproximada:", solucion)

Sistema b):
Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]
Iteración 3: [0.991 0.945 0.782]
Iteración 4: [0.9945 0.9555 0.789 ]
Iteración 5: [0.99555 0.95725 0.7911 ]
Convergencia alcanzada en 6 iteraciones
Solución aproximada: [0.995725 0.957775 0.79145 ]


In [16]:
# Sistema c)
A = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8,1], [0, 0, 1, 5]])
b = np.array([6, 25, -11, 11])
x0 = np.zeros(len(b))  # x(0) = 0

print("Sistema c):")
solucion = jacobi(A, b, x0)
print("Solución aproximada:", solucion)

Sistema c):
Iteración 1: [ 0.6    2.5   -1.375  2.2  ]
Iteración 2: [-0.65   1.65  -0.4    2.475]
Iteración 3: [-0.225     2.665    -0.859375  2.28    ]
Iteración 4: [-0.7325    2.26875  -0.3275    2.371875]
Iteración 5: [-0.534375    2.73525    -0.53710937  2.2655    ]
Iteración 6: [-0.767625    2.55234375 -0.2905625   2.30742188]
Iteración 7: [-0.67617188  2.7675875  -0.38725586  2.2581125 ]
Iteración 8: [-0.78379375  2.68318359 -0.27347031  2.27745117]
Iteración 9: [-0.7415918   2.78250875 -0.3180896   2.25469406]
Iteración 10: [-0.79125438  2.74356006 -0.26558238  2.26361792]
Iteración 11: [-0.77178003  2.78939423 -0.28617221  2.25311648]
Iteración 12: [-0.79469712  2.77142113 -0.26194244  2.25723444]
Iteración 13: [-0.78571057  2.79257158 -0.27144374  2.25238849]
Iteración 14: [-0.79628579  2.78427779 -0.26026277  2.25428875]
Iteración 15: [-0.79213889  2.79403779 -0.2646472   2.25205255]
Iteración 16: [-0.79701889  2.79021057 -0.25948768  2.25292944]
Iteración 17: [-0.79510528  2

In [17]:
# Sistema d)
A = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5,-1,-1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6,6])
x0 = np.zeros(len(b))  # x(0) = 0


print("Sistema d):")
solucion = jacobi(A, b, x0)
print("Solución aproximada:", solucion)

Sistema d):
Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]
Iteración 3: [ 0.89375 -1.35     1.81     1.83125  2.28125]
Iteración 4: [ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ]
Iteración 5: [ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396]
Iteración 6: [ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578]
Iteración 7: [ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699]
Iteración 8: [ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716]
Iteración 9: [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]
Iteración 10: [ 0.78718101 -1.00174151  1.8658388   1.91274157  1.98672138]
Iteración 11: [ 0.78729533 -1.00286688  1.86536849  1.91281957  1.98914507]
Convergencia alcanzada en 12 iteraciones
Solución aproximada: [ 0.78708833 -1.00303576  1.86604817  1.91244923  1.98957067]


**4) Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.**

In [36]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-3, max_iter=100):
    """
    Método de Gauss-Seidel para resolver un sistema Ax = b con tolerancia.

    Parámetros:
    A -- Matriz de coeficientes
    b -- Vector de términos independientes
    x0 -- Vector inicial
    tol -- Tolerancia para el criterio de parada
    max_iter -- Número máximo de iteraciones

    Retorna:
    x -- Aproximación de la solución
    """
    n = len(A)
    x = x0.copy()

    for k in range(max_iter):
        x_new = x.copy()
        for i in range(n):
            sum1 = sum(A[i][j] * x_new[j] for j in range(i))  # Elementos antes de x_i (ya actualizados)
            sum2 = sum(A[i][j] * x[j] for j in range(i + 1, n))  # Elementos después de x_i (sin actualizar)
            x_new[i] = (b[i] - sum1 - sum2) / A[i][i]  # Nueva aproximación de x_i

        # Criterio de parada
        error = np.linalg.norm(x_new - x, ord=np.inf)  # Norma infinito (máxima diferencia entre iteraciones)
        print(f"Iteración {k+1}: {x_new}, Error: {error:.5f}")

        if error < tol:
            print("Convergencia alcanzada")
            return x_new

        x = x_new

    print("Máximo número de iteraciones alcanzado")
    return x




In [37]:
#Sistema (a)
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = np.zeros(len(b))  # x(0) = 0
tol = 1e-3  # Tolerancia

print("\n Sistema (a) con Gauss-Seidel y TOL =", tol)
gauss_seidel(A, b, x0, tol)


 Sistema (a) con Gauss-Seidel y TOL = 0.001
Iteración 1: [ 0.33333333 -0.16666667  0.5       ], Error: 0.50000
Iteración 2: [ 0.11111111 -0.22222222  0.61904762], Error: 0.22222
Iteración 3: [ 0.05291005 -0.23280423  0.64852608], Error: 0.05820
Iteración 4: [ 0.03955656 -0.23595364  0.65559875], Error: 0.01335
Iteración 5: [ 0.0361492  -0.23660752  0.65733928], Error: 0.00341
Iteración 6: [ 0.03535107 -0.23678863  0.65775895], Error: 0.00080
Convergencia alcanzada


array([ 0.03535107, -0.23678863,  0.65775895])

In [38]:
#Sistema (b)
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = np.zeros(len(b))  # x(0) = 0
tol = 1e-3  # Tolerancia

print("\n Sistema (a) con Gauss-Seidel y TOL =", tol)
gauss_seidel(A, b, x0, tol)


 Sistema (a) con Gauss-Seidel y TOL = 0.001
Iteración 1: [0.9   0.79  0.758], Error: 0.90000
Iteración 2: [0.979  0.9495 0.7899], Error: 0.15950
Iteración 3: [0.99495  0.957475 0.791495], Error: 0.01595
Iteración 4: [0.9957475  0.95787375 0.79157475], Error: 0.00080
Convergencia alcanzada


array([0.9957475 , 0.95787375, 0.79157475])

In [39]:
#Sistema (c)
A = np.array([[10, 5, 0, 0], [5, 10, -4, 0], [0, -4, 8,1], [0, 0, 1, 5]])
b = np.array([6, 25, -11, 11])
x0 = np.zeros(len(b))  # x(0) = 0
tol = 1e-3  # Tolerancia

print("\n Sistema (a) con Gauss-Seidel y TOL =", tol)
gauss_seidel(A, b, x0, tol)


 Sistema (a) con Gauss-Seidel y TOL = 0.001
Iteración 1: [ 0.6    2.2   -0.275  2.255], Error: 2.25500
Iteración 2: [-0.5       2.64     -0.336875  2.267375], Error: 1.10000
Iteración 3: [-0.72        2.72525    -0.29579688  2.25915938], Error: 0.22000
Iteración 4: [-0.762625    2.76299375 -0.27589805  2.25517961], Error: 0.04262
Iteración 5: [-0.78149687  2.78038922 -0.26670284  2.25334057], Error: 0.01887
Iteración 6: [-0.79019461  2.78841617 -0.26245949  2.2524919 ], Error: 0.00870
Iteración 7: [-0.79420808  2.79212025 -0.26050136  2.25210027], Error: 0.00401
Iteración 8: [-0.79606012  2.79382952 -0.25959778  2.25191956], Error: 0.00185
Iteración 9: [-0.79691476  2.79461827 -0.25918081  2.25183616], Error: 0.00085
Convergencia alcanzada


array([-0.79691476,  2.79461827, -0.25918081,  2.25183616])

In [40]:
#Sistema (c)
A = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5,-1,-1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b = np.array([6, 6, 6, 6,6])
x0 = np.zeros(len(b))  # x(0) = 0
tol = 1e-3  # Tolerancia

print("\n Sistema (a) con Gauss-Seidel y TOL =", tol)
gauss_seidel(A, b, x0, tol)


 Sistema (a) con Gauss-Seidel y TOL = 0.001
Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375], Error: 2.64375
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453], Error: 0.97865
Iteración 3: [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ], Error: 0.48605
Iteración 4: [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533], Error: 0.06794
Iteración 5: [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365], Error: 0.01125
Iteración 6: [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692], Error: 0.00414
Iteración 7: [ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976], Error: 0.00052
Convergencia alcanzada


array([ 0.78668253, -1.00271872,  1.86628339,  1.9125618 ,  1.98978976])

**5)**

In [44]:
import numpy as np

def jacobi(A, b, x0, iterations=27):
    """Método de Jacobi para resolver Ax = b"""
    D = np.diag(np.diag(A))  # Matriz diagonal
    R = A - D  # Parte restante
    D_inv = np.linalg.inv(D)  # Inversa de la diagonal

    x = x0.copy()
    for k in range(iterations):
        x_new = np.dot(D_inv, b - np.dot(R, x))
        print(f"Iteración {k+1}: {x_new}")

    return x_new

def gauss_seidel(A, b, x0, tol=1e-5, max_iter=100):
    """Método de Gauss-Seidel para resolver Ax = b con tolerancia"""
    n = len(A)
    x = x0.copy()

    for k in range(max_iter):
        x_new = x.copy()
        for i in range(n):
            sum1 = sum(A[i][j] * x_new[j] for j in range(i))
            sum2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - sum1 - sum2) / A[i][i]

        error = np.linalg.norm(x_new - x, ord=np.inf)
        print(f"Iteración {k+1}: {x_new}, Error: {error:.6f}")

        if error < tol:
            print("Convergencia alcanzada")
            return x_new

        x = x_new

    print("Máximo número de iteraciones alcanzado")
    return x

#Definimos el sistema
A = np.array([[2, -1, 1], [2, 2, 2], [-1, -1, 2]])
b = np.array([-1, 4, -5])
x0 = np.zeros(len(b))  # x(0) = 0

# 🔹 a) Método de Jacobi con 25 iteraciones
print("\n Método de Jacobi (25 iteraciones):")
jacobi(A, b, x0)

# 🔹 b) Método de Gauss-Seidel con tolerancia 10^-5
print("\n Método de Gauss-Seidel con TOL = 10^-5:")
gauss_seidel(A, b, x0, tol=1e-5)



 Método de Jacobi (25 iteraciones):
Iteración 1: [-0.5  2.  -2.5]
Iteración 2: [-0.5  2.  -2.5]
Iteración 3: [-0.5  2.  -2.5]
Iteración 4: [-0.5  2.  -2.5]
Iteración 5: [-0.5  2.  -2.5]
Iteración 6: [-0.5  2.  -2.5]
Iteración 7: [-0.5  2.  -2.5]
Iteración 8: [-0.5  2.  -2.5]
Iteración 9: [-0.5  2.  -2.5]
Iteración 10: [-0.5  2.  -2.5]
Iteración 11: [-0.5  2.  -2.5]
Iteración 12: [-0.5  2.  -2.5]
Iteración 13: [-0.5  2.  -2.5]
Iteración 14: [-0.5  2.  -2.5]
Iteración 15: [-0.5  2.  -2.5]
Iteración 16: [-0.5  2.  -2.5]
Iteración 17: [-0.5  2.  -2.5]
Iteración 18: [-0.5  2.  -2.5]
Iteración 19: [-0.5  2.  -2.5]
Iteración 20: [-0.5  2.  -2.5]
Iteración 21: [-0.5  2.  -2.5]
Iteración 22: [-0.5  2.  -2.5]
Iteración 23: [-0.5  2.  -2.5]
Iteración 24: [-0.5  2.  -2.5]
Iteración 25: [-0.5  2.  -2.5]
Iteración 26: [-0.5  2.  -2.5]
Iteración 27: [-0.5  2.  -2.5]

 Método de Gauss-Seidel con TOL = 10^-5:
Iteración 1: [-0.5  2.5 -1.5], Error: 2.500000
Iteración 2: [ 1.5   2.   -0.75], Error: 2.000

array([ 1.00000226,  1.9999975 , -1.00000012])

**6)**

In [45]:
import numpy as np

def gauss_seidel(A, b, x0, tol=1e-2, max_iter=300):
    """Método de Gauss-Seidel para resolver Ax = b"""
    n = len(A)
    x = x0.copy()

    for k in range(max_iter):
        x_new = x.copy()
        for i in range(n):
            sum1 = sum(A[i][j] * x_new[j] for j in range(i))  # Elementos ya actualizados
            sum2 = sum(A[i][j] * x[j] for j in range(i + 1, n))  # Elementos sin actualizar
            x_new[i] = (b[i] - sum1 - sum2) / A[i][i]

        error = np.linalg.norm(x_new - x, ord=np.inf)
        print(f"Iteración {k+1}: {x_new}, Error: {error:.6f}")

        if error < tol:
            print("Convergencia alcanzada")
            return x_new

        x = x_new

    print("Máximo número de iteraciones alcanzado")
    return x

# Definimos el sistema
A = np.array([
    [1, 0, -1],
    [-1/2, 1, -1/4],
    [1, -1/2, 1]
])
b = np.array([0.2, -1.425, 2])
x0 = np.zeros(len(b))  # x(0) = 0

# 🔹 Ejecutamos Gauss-Seidel
print("\n Método de Gauss-Seidel con TOL = 10^-2:")
sol = gauss_seidel(A, b, x0, tol=1e-2, max_iter=300)
print(f"\nSolución aproximada: {sol}")



 Método de Gauss-Seidel con TOL = 10^-2:
Iteración 1: [ 0.2    -1.325   1.1375], Error: 1.325000
Iteración 2: [ 1.3375    -0.471875   0.4265625], Error: 1.137500
Iteración 3: [ 0.6265625  -1.00507813  0.87089844], Error: 0.710938
Iteración 4: [ 1.07089844 -0.67182617  0.59318848], Error: 0.444336
Iteración 5: [ 0.79318848 -0.88010864  0.7667572 ], Error: 0.277710
Iteración 6: [ 0.9667572  -0.7499321   0.65827675], Error: 0.173569
Iteración 7: [ 0.85827675 -0.83129244  0.72607703], Error: 0.108480
Iteración 8: [ 0.92607703 -0.78044223  0.68370185], Error: 0.067800
Iteración 9: [ 0.88370185 -0.81222361  0.71018634], Error: 0.042375
Iteración 10: [ 0.91018634 -0.79236024  0.69363354], Error: 0.026484
Iteración 11: [ 0.89363354 -0.80477485  0.70397904], Error: 0.016553
Iteración 12: [ 0.90397904 -0.79701572  0.6975131 ], Error: 0.010346
Iteración 13: [ 0.8975131  -0.80186517  0.70155431], Error: 0.006466
Convergencia alcanzada

Solución aproximada: [ 0.8975131  -0.80186517  0.70155431]


**8)**

In [46]:
import numpy as np

# Definir la matriz A y el vector b
A = np.array([
    [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0],
    [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0],
    [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
    [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0],
    [0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, -1, 0, 0, 0, -1, 4]
])

b = np.array([220, 110, 110, 220, 110, 110, 110, 220, 110, 220, 110])

# a. Verificar si la matriz es estrictamente diagonalmente dominante
def es_diagonalmente_dominante(A):
    for i in range(len(A)):
        suma_fila = np.sum(np.abs(A[i])) - np.abs(A[i, i])
        if np.abs(A[i, i]) <= suma_fila:
            return False
    return True

print("¿La matriz es estrictamente diagonalmente dominante?", es_diagonalmente_dominante(A))

# b. Método de Jacobi
def jacobi(A, b, x0, tol, max_iter=1000):
    n = len(b)
    x = x0.copy()
    for k in range(max_iter):
        x_nuevo = np.zeros_like(x)
        for i in range(n):
            suma = np.dot(A[i, :], x) - A[i, i] * x[i]
            x_nuevo[i] = (b[i] - suma) / A[i, i]
        if np.linalg.norm(x_nuevo - x) < tol:
            return x_nuevo
        x = x_nuevo
    return x

x0 = np.zeros_like(b)
tol = 10 * 2
solucion_jacobi = jacobi(A, b, x0, tol)
print("Solución usando Jacobi:", solucion_jacobi)

# c. Método de Gauss-Seidel
def gauss_seidel(A, b, x0, tol, max_iter=1000):
    n = len(b)
    x = x0.copy()
    for k in range(max_iter):
        x_nuevo = x.copy()
        for i in range(n):
            suma = np.dot(A[i, :], x_nuevo) - A[i, i] * x_nuevo[i]
            x_nuevo[i] = (b[i] - suma) / A[i, i]
        if np.linalg.norm(x_nuevo - x) < tol:
            return x_nuevo
        x = x_nuevo
    return x

solucion_gauss_seidel = gauss_seidel(A, b, x0, tol)
print("Solución usando Gauss-Seidel:", solucion_gauss_seidel)

¿La matriz es estrictamente diagonalmente dominante? True
Solución usando Jacobi: [82 61 61 84 60 68 56 85 68 84 62]
Solución usando Gauss-Seidel: [82 62 63 86 61 69 58 88 70 88 66]
